module.exports = {
	teamData:
	[
		{
			id: 1,
			firstName: 'Gary',
			surname: 'Chadwick',
			teamName: 'Is there a loo on Mont Ventoux?',
			ranking: '1',
			cost: '100',
			location: 'United Kingdom',
			riderData: [
				{
					firstName: 'Chris',
					surname: 'Froome',
					team: 'Sky',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '1985'
				},
				{
					firstName: 'Adam',
					surname: 'Yates',
					team: 'Orica BikeExchange',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '890'
				},
				{
					firstName: 'Vincenzo',
					surname: 'Nibili',
					team: 'Astana',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '324'
				},
				{
					firstName: 'Jurgen',
					surname: 'Van Den Broeck',
					team: 'Katusha',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '36'
				},
				{
					firstName: 'Marcel',
					surname: 'Kittel',
					team: 'Etixx-Quickstep',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '931'
				},
				{
					firstName: 'Ian',
					surname: 'Stannard',
					team: 'Sky',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '177'
				},
				{
					firstName: 'Vasil',
					surname: 'Kiryienka',
					team: 'Sky',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '176'
				},
				{
					firstName: 'Tony',
					surname: 'Martin',
					team: 'Etixx-Quickstep',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '167'
				},
				{
					firstName: 'Thomas',
					surname: 'Voeckler',
					team: 'Direct Energie',
					cost: '20',
					stageScore: '678',
					gcScore: '900',
					pcScore: '20',
					komScore: '90',
					sprintScore: '6',
					sumScore: '29',
					bkyScore: '8',
					assScore: '11',
					total: '114'
				}
			]
		}
	]
};